version: "3.10"

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: aiogram_bot
    restart: always
    volumes:
      - ./data.json:/app/data.json  # Монтируем конкретный JSON-файл
      - .:/app  # Остальной код проекта
